apiVersion: addons.sigs.k8s.io/v1alpha1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # The name of your cluster. If omitted, this cluster cannot be selected by
  # a ClusterSelector.
  clusterName: standard-cluster-1
  git:
    syncRepo: git@github.com:jbrook/csp-config-management.git
    syncBranch: 0.1.0
    secretType: ssh
    policyDir: "foo-corp"
